services:
  web:
    build:
      context: ./gestecord
    #   dockerfile: 'dockerfile.dev'
    # volumes:
    #   - ./gestecord:/tmp/web
    ports:
      - 8080:80
  db:
    image: mongo:7.0.5-jammy
    command: --quiet
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=gestecord
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
