name: Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@master

    
    - name: Build and Deploy
      run: |
        npm run build